AspNetCoreMvc-eTicaret-MovieSales/Controllers/CustomerController.cs
using AspNetCoreMvc_eTicaret_MovieSales.Data;
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.Models;
using AspNetCoreMvc_eTicaret_MovieSales.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.Controllers
{
    public class CustomerController : Controller
    {

        private readonly ICustomerRepository _customerRepo;
        private readonly IMovieSaleRepository _movieSaleRepository;
        private readonly IMovieSaleDetailRepository _movieDetailSaleRepository;

        private readonly IMapper _mapper;
        public CustomerController(ICustomerRepository customerRepo, IMapper mapper, IMovieSaleRepository movieSaleRepository)
        {
            _customerRepo = customerRepo;
            _mapper = mapper;
            _movieSaleRepository = movieSaleRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(CustomerLoginViewModel model) 
        {
            if (ModelState.IsValid) 
            {
                var customer = _customerRepo.GetAll().FirstOrDefault(c => c.Email == model.Email &&  c.Password == model.Password);
                if (customer == null) 
                {
                    ModelState.AddModelError(string.Empty, "Hatalı email veya şifre girişi");
                }
                else
                {
                    HttpContext.Session.SetJson("user", customer);
                    return RedirectToAction("ConfirmAddress");
                }
            }
            return View(model);
        }
        public IActionResult ConfirmAddress()
        {

            //Dışarıdan gelebilecek ataklara karşı öncelikle kullanıcıyı session'dan çekp kontrol ediyoruz.

            var customer = HttpContext.Session.GetJson<Customer>("user");
            if (customer == null)
            {
                return RedirectToAction("Login");
            }
            
            return View(_mapper.Map<CustomerViewModel>(customer));
        }

        [HttpPost]
        public IActionResult ConfirmAddress(CustomerViewModel model)
        {
            _customerRepo.Update(_mapper.Map<Customer>(model));
            HttpContext.Session.SetJson("user", model);
            return RedirectToAction("ConfirmPayment");

        }


        public IActionResult ConfirmPayment() 

        {
            var customer = HttpContext.Session.GetJson<Customer>("user");
            if (customer == null)
            {
                return RedirectToAction("Login");
            }
            //sepet bilgileri session'dan çekilecek.
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet");
            SepetDetay sd = new SepetDetay();
            int toplamAdet = sd.ToplamAdet(sepet);
            decimal toplamTutar = sd.ToplamTutar(sepet);

            MovieSaleViewModel movieSaleViewModel = new MovieSaleViewModel();
            movieSaleViewModel.CustomerId = customer.Id;
            movieSaleViewModel.Date = DateTime.Now;
            movieSaleViewModel.TotalQuantity = toplamAdet;
            movieSaleViewModel.TotalPrice = toplamTutar;
            
            CustomerFaturaViewModel customerFaturaViewModel = new CustomerFaturaViewModel()
            {
                customerViewModel = _mapper.Map<CustomerViewModel>(customer),
                satisViewModel = movieSaleViewModel,
                sepetDetayListesi = sepet

            };


            return View(customerFaturaViewModel);

        }
        [HttpPost]
        public IActionResult ConfirmPayment(CustomerFaturaViewModel model)
        {
            var satisId = _movieSaleRepository.AddSale(_mapper.Map<MovieSale>(model.satisViewModel));

            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet");

            if(_movieDetailSaleRepository.AddRange(sepet, satisId))
            {
                TempData["mesaj"] = "Satış işlemi başarıyla gerçekleşti.";
                HttpContext.Session.Remove("sepet"); // sepet bilgileri session'dan silinir.ancak müşteri isterse yeniden alışverişe devam edebilir.
            }
            else
            {
                TempData["mesaj"] = "Satış işlemi gerçekleşmedi, bilgilerinizi kontol edin !";

            }
            return View("MessageShow");
        }

        public IActionResult Create() 
        {
            return View();
        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Controllers/MovieController.cs
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.Models;
using AspNetCoreMvc_eTicaret_MovieSales.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;

        public MovieController(IMovieRepository movieRepo, IMapper mapper)
        {
            _movieRepo = movieRepo;
            _mapper = mapper;
        }

        private readonly IMapper _mapper;
        SepetDetay siparis = new SepetDetay();
        public IActionResult Index(int? id, string? search)


        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();

            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);

            var movies = _movieRepo.GetAll();
            if(search != null)
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            if (id != null)
            {
                movies = movies.Where(m => m.GenreId == id).ToList();
            }
            return View(movies);
        }

        public IActionResult Populer()
        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


            var movies = _movieRepo.GetAll().Where(m => m.IsPopuler == true).ToList();
            return View(movies);
        }

        public IActionResult Local(bool isLocal)
        {
            var movies = _movieRepo.GetAll();
            if (isLocal)
            {
                var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
                TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


                movies = movies.Where(m => m.IsLocal == true).ToList();
                 ViewBag.Local = "Yerli";
            }
            else 
            {
                var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
                TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);
                movies = movies.Where(m => m.IsLocal == false).ToList();
                 ViewBag.Local = "Yabancı";
            }


            return View(movies);
        }
        public IActionResult Details(int id) 
        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


            var movies = _movieRepo.Get(id);
            return View(movies);
        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Controllers/SepetController.cs
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.Controllers
{
    public class SepetController : Controller
    {
        private readonly IMovieRepository _movieRepo;

        public SepetController(IMovieRepository movieRepo)
        {
            _movieRepo = movieRepo;
        }
        List<SepetDetay> sepet;
        SepetDetay siparis = new SepetDetay();

        public IActionResult Index()
        {
            sepet = SepetAl();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);
            
            TempData["ToplamTutar"] = siparis.ToplamTutar(sepet);

            return View(sepet);
        }

        public IActionResult Ekle(int Id, int Adet)
        {
            
            var movie = _movieRepo.Get(Id);
            sepet = SepetAl();
            SepetDetay siparis = new SepetDetay();
            siparis.MovieId = movie.Id;
            siparis.MovieName = movie.Name;
            siparis.MovieQuantity = Adet;
            siparis.MoviePrice = movie.Price;
            sepet = siparis.SepeteEkle(sepet, siparis);
            SepetKaydet(sepet);
            return RedirectToAction("Index");
        }

        public IActionResult SepetSil()
        {
            //HttpContext.Session.Clear(); //Oturumda bulunan tüm sessionları siler.
            HttpContext.Session.Remove("sepet"); //Sadece ismi belirtiler sessionı siler.
            return RedirectToAction("Index");
        }

        public IActionResult Sil(int id)
        {
            sepet = SepetAl();
            sepet =siparis.SepettenSil(sepet, id);
            SepetKaydet(sepet);
            return RedirectToAction("Index");
        }
        public List<SepetDetay> SepetAl() 
        
        {

            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            return sepet;
        }

        public void SepetKaydet(List<SepetDetay> sepet)

        {
            HttpContext.Session.SetJson("sepet", sepet);


        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Views/Sepet/Index.cshtml
@model List<SepetDetay>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Movie.cshtml";
}

<h2>Sepet Biggileri</h2>
<
<table class="table table-striped table-primary">

    <thead>
        <tr>
            <th>Film Adı</th>
            <th>Birim Fiyat</th>
            <th>Adet</th>
            <th>Tutar</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var siparis in Model)
        {
            <tr>
                <td>@siparis.MovieName</td>
                <td>@siparis.MoviePrice</td>
                <td>@siparis.MovieQuantity</td>
                <td>@(siparis.MovieQuantity * siparis.MoviePrice)</td>

                <td>
                    <a class="btn btn-primary ms-8" asp-controller="Sepet" asp-action="Sil" asp-route-id="@siparis.MovieId">
                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                            <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5" />
                        </svg>
                    </a>
                </td>
            </tr>
        }
        <tr class="fw-bold">
            <td>Toplam : </td>
            <td></td>
            <td>
                @if (TempData["ToplamAdet"] != null)
                {
                    @TempData["ToplamAdet"]
                }
            </td>
            <td>
                @if (TempData["ToplamTutar"] != null)
                {
                    @TempData["ToplamTutar"]
                }
            </td>
            <td>
                <a class="btn btn-primary" asp-controller="Sepet" asp-action="SepetSil">Tümünü Sil</a>
            </td>
        </tr>
    </tbody>
</table>
<div class="text-center">
    <a class="btn btn-primary" asp-controller="Movie" asp-action="Index">Alışverişe Devam</a>
    <a class="btn btn-primary" asp-controller="Customer" asp-action="Login">Sepeti Onayla</a>

</div>