AspNetCoreMvc-eTicaret-MovieSales/Models/Movie.cs
namespace AspNetCoreMvc_eTicaret_MovieSales.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public string Summary { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int Stock { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public bool IsLocal { get; set; }
        public bool IsPopuler { get; set; }
        public bool IsDiscount { get; set; }

        public int GenreId { get; set; }

        //Navigation Property (Relations)

        public Genre Genre { get; set; }
        public List<MovieSaleDetail> MovieSaleDetails { get; set; }

    }
}

AspNetCoreMvc-eTicaret-MovieSales/ViewModels/MovieViewModel.cs
namespace AspNetCoreMvc_eTicaret_MovieSales.ViewModels
{
    public class MovieViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Cast { get; set; }
        public string Summary { get; set; }
        public DateTime ReleaseDate { get; set; }
        public int Stock { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public bool IsLocal { get; set; }
        public bool IsPopuler { get; set; }
        public bool IsDiscount { get; set; }

        public int GenreId { get; set; }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Controllers/MovieController.cs
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.Models;
using AspNetCoreMvc_eTicaret_MovieSales.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.Controllers
{
    public class MovieController : Controller
    {
        private readonly IMovieRepository _movieRepo;

        public MovieController(IMovieRepository movieRepo, IMapper mapper)
        {
            _movieRepo = movieRepo;
            _mapper = mapper;
        }

        private readonly IMapper _mapper;
        SepetDetay siparis = new SepetDetay();
        public IActionResult Index(int? id, string? search)


        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();

            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);

            var movies = _movieRepo.GetAll();
            if(search != null)
            {
                movies = movies.Where(m => m.Name.ToLower().Contains(search.ToLower())).ToList();
            }
            if (id != null)
            {
                movies = movies.Where(m => m.GenreId == id).ToList();
            }
            return View(movies);
        }

        public IActionResult Populer()
        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


            var movies = _movieRepo.GetAll().Where(m => m.IsPopuler == true).ToList();
            return View(movies);
        }

        public IActionResult Local(bool isLocal)
        {
            var movies = _movieRepo.GetAll();
            if (isLocal)
            {
                var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
                TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


                movies = movies.Where(m => m.IsLocal == true).ToList();
                 ViewBag.Local = "Yerli";
            }
            else 
            {
                var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
                TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);
                movies = movies.Where(m => m.IsLocal == false).ToList();
                 ViewBag.Local = "Yabancı";
            }


            return View(movies);
        }
        public IActionResult Details(int id) 
        {
            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);


            var movies = _movieRepo.Get(id);
            return View(movies);
        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Controllers/SepetController.cs
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.Controllers
{
    public class SepetController : Controller
    {
        private readonly IMovieRepository _movieRepo;

        public SepetController(IMovieRepository movieRepo)
        {
            _movieRepo = movieRepo;
        }
        List<SepetDetay> sepet;
        SepetDetay siparis = new SepetDetay();

        public IActionResult Index()
        {
            sepet = SepetAl();
            TempData["ToplamAdet"] = siparis.ToplamAdet(sepet);
            
            TempData["ToplamTutar"] = siparis.ToplamTutar(sepet);

            return View(sepet);
        }

        public IActionResult Ekle(int Id, int Adet)
        {
            
            var movie = _movieRepo.Get(Id);
            sepet = SepetAl();
            SepetDetay siparis = new SepetDetay();
            siparis.MovieId = movie.Id;
            siparis.MovieName = movie.Name;
            siparis.MovieQuantity = Adet;
            siparis.MoviePrice = movie.Price;
            sepet = siparis.SepeteEkle(sepet, siparis);
            SepetKaydet(sepet);
            return RedirectToAction("Index");
        }

        public IActionResult SepetSil()
        {
            //HttpContext.Session.Clear(); //Oturumda bulunan tüm sessionları siler.
            HttpContext.Session.Remove("sepet"); //Sadece ismi belirtiler sessionı siler.
            return RedirectToAction("Index");
        }

        public IActionResult Sil(int id)
        {
            sepet = SepetAl();
            sepet =siparis.SepettenSil(sepet, id);
            SepetKaydet(sepet);
            return RedirectToAction("Index");
        }
        public List<SepetDetay> SepetAl() 
        
        {

            var sepet = HttpContext.Session.GetJson<List<SepetDetay>>("sepet") ?? new List<SepetDetay>();
            return sepet;
        }

        public void SepetKaydet(List<SepetDetay> sepet)

        {
            HttpContext.Session.SetJson("sepet", sepet);


        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/ViewComponents/GenresViewComponent.cs
using AspNetCoreMvc_eTicaret_MovieSales.Interfaces;
using AspNetCoreMvc_eTicaret_MovieSales.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCoreMvc_eTicaret_MovieSales.ViewComponents
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly IGenreRepository _genreRepo;
        private readonly IMapper _mapper;
        public GenresViewComponent(IGenreRepository genreRepo, IMapper mapper)
        {
            _genreRepo = genreRepo;
            _mapper = mapper;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            ViewBag.SelectedGenreId = RouteData?.Values["id"];
            var genres = _genreRepo.GetAll();
            return View(_mapper.Map<List<GenreViewModel>>(genres));

        }
    }
}

AspNetCoreMvc-eTicaret-MovieSales/Views/Movie/Details.cshtml
@model Movie
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout_Movie.cshtml";
}

<h2>Film Detayları</h2>

<div class="card mb-3">
    <div class="card-header">
        <h4 class="card-title">@Model.Name</h4>
    </div>
    <div class="row g-0">
        <div class="col-6">
            <img src="@Model.ImageUrl" class="card-img-top" title="@Model.Name" alt="@Model.Name" />
        </div>
        <div class="col-6">
            <div class="card-body">
                <p class="fs-5"><b>Yönetmen  :</b> @Model.Director</p>
                <p class="fs-5"><b>Oyuncular :</b> @Model.Cast</p>
                <p class="fs-5"><b>Özet :</b> @Model.Summary</p>
                <p class="fs-5">Son derece heyecanlı bir aksiyon filmi. Tempo hiç düşmüyor. Özellikle nefes kesici bir finali var.</p>

            </div>
        </div>
    </div>
    <div class="card-footer ">
        <form asp-controller="Sepet" asp-action="Ekle" method="get">
            <input type="hidden" name="Id" value="@Model.Id" />
                <span class="card-text">@string.Format("{0:C2}", @Model.Price)</span>
                    <input class="mx-5" type="number" name="Adet" value="1" min="1" max="@Model.Stock" />
                        <button type="submit" class="btn btn-primary">
                            Sepete At
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0" />
                                </svg>
                        </button>
        </form>
    </div>
    
</div>

@section GenreMenu {
    @await Component.InvokeAsync("Genres")
}

AspNetCoreMvc-eTicaret-MovieSales/Views/Movie/Index.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout_Movie.cshtml";
}

<h2>Tüm Filmer</h2>

<div class="row">
    @if (Model.Count() > 0)
        @foreach (var film in Model)
        {
            <div class="col-md-3">
                <div class="card mb-3">
                   <form asp-controller="Sepet" asp-action="Ekle" method="get">
                        <input type="hidden" name="Id" value="@film.Id" />
                    <div class="card-header text-center">
                        <h5 class="card-title"> @film.Name    </h5>
                    </div>
                    <a href="/Movie/Details/@film.Id">
                        <img src="@film.ImageUrl" class="card-img-top" title="@film.Name" alt="@film.Name" />
                    </a>
                    <div class="card-body text-center">
                        <span class="card-text">@string.Format("{0:C2}", @film.Price)</span>
                        <input type="number" name="Adet" value="1" min="1" max="@film.Stock" />
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-primary">
                            Sepete At
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0" />
                            </svg>
                        </button>
                    </div>
                    </form>
                </div>
            </div>

        }

    else
    {
        <div class="alert alert-warning" role="alert">
            <strong>İstenilen türde film bulunmamaktadır!</strong>
        </div>
    }
</div>

@section GenreMenu {
    @await Component.InvokeAsync("Genres")
}

AspNetCoreMvc-eTicaret-MovieSales/Views/Movie/Local.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "Local";
    Layout = "~/Views/Shared/_Layout_Movie.cshtml";
}

<h1>@ViewBag.Local Filmler</h1>

<div class="row">
    @if (Model.Count() > 0)
        @foreach (var film in Model)
        {
            <div class="col-md-3">
                <div class="card mb-3">


                    <form asp-controller="Sepet" asp-action="Ekle" method="get">
                        <input type="hidden" name="Id" value="@film.Id" />
                        <div class="card-header text-center">
                            <h5 class="card-title"> @film.Name    </h5>
                        </div>
                        <a href="/Movie/Details/@film.Id">
                            <img src="@film.ImageUrl" class="card-img-top" title="@film.Name" alt="@film.Name" />
                        </a>
                        <div class="card-body text-center">
                            <span class="card-text">@string.Format("{0:C2}", @film.Price)</span>
                            <input type="number" name="Adet" value="1" min="1" max="@film.Stock" />
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-primary">
                                Sepete At
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                    <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0" />
                                </svg>
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        }

    else
    {
        <div class="alert alert-warning" role="alert">
            <strong>İstenilen türde film bulunmamaktadır!</strong>
        </div>
    }
</div>

@section GenreMenu {
    @await Component.InvokeAsync("Genres")
}

AspNetCoreMvc-eTicaret-MovieSales/Views/Movie/Populer.cshtml
@model List<Movie>
@{
    ViewData["Title"] = "Populer";
    Layout = "~/Views/Shared/_Layout_Movie.cshtml";
}

<h1>Populer</h1>

<div class="row">
    @if (Model.Count() > 0)
        @foreach (var film in Model)
        {
            <div class="col-md-3">
                <div class="card mb-3">
                    <div class="card-header text-center">
                        <h5 class="card-title"> @film.Name    </h5>
                    </div>
                    <a href="/Movie/Details/@film.Id">
                        <img src="@film.ImageUrl" class="card-img-top" title="@film.Name" alt="@film.Name" />
                    </a>
                    <div class="card-body text-center">
                        <span class="card-text">@string.Format("{0:C2}", @film.Price)</span>
                        <input type="number" name="Adet" value="1" min="1" max="@film.Stock" />
                    </div>
                    <div class="card-footer text-center">
                        <button type="submit" class="btn btn-primary">
                            Sepete At
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cart-plus-fill" viewBox="0 0 16 16">
                                <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0m7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0M9 5.5V7h1.5a.5.5 0 0 1 0 1H9v1.5a.5.5 0 0 1-1 0V8H6.5a.5.5 0 0 1 0-1H8V5.5a.5.5 0 0 1 1 0" />
                            </svg>
                        </button>
                    </div>

                </div>
            </div>

        }

    else
    {
        <div class="alert alert-warning" role="alert">
            <strong>İstenilen türde film bulunmamaktadır!</strong>
        </div>
    }
</div>

@section GenreMenu {
    @await Component.InvokeAsync("Genres")
}